name: Continuous Integration
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Check code style
      - name: Check code style
        run: npm run lint

      # Generate a random JWT secret
      - name: Generate a random JWT secret
        id: generate-secret
        run: echo "::set-output name=JWT_SECRET::$(openssl rand -base64 30)"
        shell: bash

      # Start Docker Compose
      - name: Start Docker Compose
        run: docker-compose up -d --build

      # Run tests
      - name: Run tests
        run: npm test
        env:
          MONGODB_URI: mongosh "mongodb+srv://nodejs-project.b2f6g.mongodb.net/" --apiVersion 1 --username joelcooper02 --password 85jwYd9GPiG4EF5G
          PORT: 3000
          SALT_ROUNDS: 10
          JWT_SECRET: ${{ steps.generate-secret.outputs.JWT_SECRET }}
